name: CatsAndMice
version: '1.0.3'
main: fr.Eniox59.catsandmice.CatsAndMice
api-version: '1.20.6'
authors: [ Eniox59 ]
description: Un jeu de clics avec classement et meilleur score
depend:
  - DecentHolograms

# Dépendances optionnelles
softdepend:
  - LuckPerms

commands:
  mice:
    description: Commandes du jeu CatsAndMice
    usage: /mice <create|reload>
    permission: catsandmice.command

permissions:
  catsandmice.*:
    description: Accès à toutes les fonctionnalités du plugin CatsAndMice (Admin)
    default: false
    children:
      catsandmice.command: true
      catsandmice.bypass: true
      catsandmice.reset: true
  catsandmice.command:
    description: Permet d'utiliser les commandes /mice create et /mice reload
    default: false
  catsandmice.bypass:
    description: Permet de contourner le délai entre les clics
    default: false
  catsandmice.reset:
    description: Permet de réinitialiser le score en cliquant sur l'hologramme
    default: false